Bunch of changes to prepare an official release

diff --git a/sat-rpi b/sat-rpi
--- a/sat-rpi
+++ b/sat-rpi
@@ -20,18 +20,15 @@ rootfs="$distro/rootfs"
 rpi_git="$rpi/git"
 kernel="$rpi_git/linux"
 firmware="$rpi_git/firmware"
-tools="$rpi_git/tools"
+dev="$2"
 
 # URLs
 rpi_mirror="http://mirror.slitaz.org/arm/rpi/"
 fw_url="https://github.com/raspberrypi/firmware/raw/master/boot/"
-tools_url="https://raw.github.com/raspberrypi/tools/master/mkimage/"
 rpi_git_url="git://github.com/raspberrypi/"
 
 # Lists
 fwlist="bootcode.bin fixup.dat start.elf"
-toolslist="imagetool-uncompressed.py args-uncompressed.txt \
-boot-uncompressed.txt"
 
 #
 # Functions
@@ -56,12 +53,11 @@ $(boldify "Commands:")
   clean         Clean the current work directory
 
 $(boldify "Options:")
-  --up          Update for commands: firmware, tools, kernel
+  --up          Update for commands: firmware and kernel
   --turbo       Force the RPi to run at the highest arm_freq
   --oclock=     Set the RPi overclocking mode in config.txt
   --vc          Install the RPi VC libraries in /opt/vc
   --nosat       Don't regenerate the distro with sat
-  --git         Remove RPi git files on clean up
 
 EOT
 }
@@ -71,7 +67,7 @@ error() {
 }
 
 header() {
-	newline && boldify "$@" && separator
+	newline && colorize 35 "$@" && separator
 }
 
 # Get minimal RPi firmware
@@ -132,6 +128,11 @@ over_voltage=$over_voltage
 EOT
 }
 
+umount_sd() {
+	umount /dev/${dev}1 2>/dev/null || exit 1
+	umount /dev/${dev}3 2>/dev/null || exit 1
+}
+
 #
 # Commands
 #
@@ -151,10 +152,8 @@ case "$1" in
 		rpiboot="/media/rpi/boot"
 		rpiroot="/media/rpi/rootfs"
 		header "SliTaz Raspberry Pi install"
-		if [ ! "$dev" ]; then
-			echo "Missing: --dev= cmdline option"
-			newline && exit 1
-		fi
+		[ "$dev" ] || echo -n "SD card device name (ex sdc): "; read dev
+		[ "$dev" ] || exit 1
 		
 		# Store sdcard partition(s) list
 		fdisk -l /dev/${dev} | grep "^/dev/$dev" | awk '{print $1}' \
@@ -168,8 +167,7 @@ case "$1" in
 		# Mount sdcard
 		if mount | grep -q "^/dev/$dev[1-3]"; then
 			debug "Unmounting: /dev/$dev"
-			umount /dev/${dev}1 2>/dev/null || exit 1
-			umount /dev/${dev}3 2>/dev/null || exit 1
+			umount_sd
 		fi
 		echo -n "Mounting: /dev/$dev partitions"
 		mkdir -p ${rpiboot} ${rpiroot}
@@ -188,12 +186,12 @@ case "$1" in
 		
 		# Unmount
 		echo -n "Unmounting: RPi sdcard"
-		umount ${rpiboot}
-		umount ${rpiroot}
-		status
+		umount_sd; status
 		
 		rm -f ${data}/sdcard.part
-		separator && newline ;;
+		separator
+		echo "Insert the SD card into your Raspberry Pi and boot!"
+		newline ;;
 		
 	ls-dev)
 		newline
@@ -219,7 +217,7 @@ case "$1" in
 			newline
 		fi
 		
-		boldify "SliTaz Raspberry Pi distro"
+		colorize 35 "SliTaz Raspberry Pi distro"
 		separator
 		mkdir -p ${boot}
 		
@@ -245,7 +243,7 @@ case "$1" in
 		done
 		status
 		
-		# TazBerry ncurses and CGI data/plugins
+		# TazBerry
 		echo -n "Copying: TazBerry..."
 		cp -f ${rpi}/tazberry ${rootfs}/usr/bin
 		cp -a ${rpi}/cgi-adm/* ${rootfs}/var/www/adm
@@ -311,8 +309,7 @@ case "$1" in
 		check_root
 		install="$data/linux-install"
 		if [ ! -d "/cross/$arch" ]; then
-			error "Missing cross toolchain in: /cross/$arch"
-			exit 1
+			error "Missing cross toolchain in: /cross/$arch" && exit 1
 		fi
 		
 		# Kernel source
@@ -379,9 +376,9 @@ EOT
 	
 	get-fw)
 		get_fw ;;
-		
-	get-tools)
-		get_tools ;;
+	
+	clone-fw)
+		clone_fw ;;
 		
 	get-linux)
 		# Precook RPi kernel
@@ -439,9 +436,6 @@ EOT
 		mkdir -p ${arch}
 		cp -a ${name}-${vers}/${arch}/* ${arch} 
 		echo "Tools path: /cross/${arch}/tools/bin" ;;
-	
-	clone-fw)
-		clone_fw ;;
 		
 	release)
 		# Used to release official SliTaz RPi images
@@ -454,30 +448,8 @@ EOT
 		dsize=$(du -sh $distro | awk '{print $1}' | cut -d "." -f 1)
 		rm -rf ${dname} && mkdir ${dname}
 		cp -a boot rootfs ${dname}
-		cat > ${dname}/README << EOT
-SliTaz Raspberry Pi - $flavor-$(date +%Y%m%d) - http://arm.slitaz.org/rpi
---------------------------------------------------------------------------------
-
-boot/   : Must be copied to a FAT32 partition
-rootfs/ : Must be copied to a ext4 or btrfs partition
-
-Manual Installation. Assuming the sdcard is /dev/sdc and has got 3 
-partitions (boot,swap,root). Mount the sdcard, copy files, unmount:
-
- # mkdir -p /media/rpi/boot /media/rpi/root
- 
- # mount /dev/sdc1 /media/rpi/boot
- # mount /dev/sdc3 /media/rpi/root
- 
- # cp -a boot/* /media/rpi/boot
- # cp -a rootfs/* /media/rpi/root
- 
- # umount /media/rpi/boot
- # umount /media/rpi/root
-
---------------------------------------------------------------------------------
-
-EOT
+		echo "Copying: SliTaz release files"
+		cp ${rpi}/release/* ${dname}
 		echo "Creating: ${dname}.tar.xz"
 		tar -cJf ${dname}.tar.xz ${dname}
 		echo "Creating: ${dname}.md5"
@@ -486,8 +458,8 @@ EOT
 	
 	clean)
 		echo "Cleaning: $rpi"
-		rm -rf ${data} 
-		[ "$git" ] && rm -rf ${rpi_git} ;;
-	*) usage ;;
+		rm -rf ${data} ${rpi_git} ;;
+		
+	*|*help) usage ;;
 esac
 exit 0
