Bunch of improvments, add /opt/vc support

diff --git a/spi b/spi
--- a/spi
+++ b/spi
@@ -11,9 +11,9 @@
 [ "$work" ] || work="$(pwd)"
 distro="$work/distro"
 rpi="$work/rpi"
-data="$rpi/distro/data"
-boot="$rpi/distro/boot"
-rootfs="$rpi/distro/rootfs"
+data="$rpi/data"
+boot="$distro/boot"
+rootfs="$distro/rootfs"
 rpi_git="$rpi/git"
 kernel="$rpi_git/linux"
 firmware="$rpi_git/firmware"
@@ -52,10 +52,11 @@ $(boldify "Commands:")
   oclock        Display overclocking information
 
 $(boldify "Options:")
-  --up          Update firmware, tools or kernel
-  --clean       Clean the distro tree (Sat can also be used)
+  --up          Update for commands: firmware, tools, kernel
   --turbo       Force the RPi to run at the highest arm_freq
-  --oclock=     Set the RPi overclocking mode
+  --oclock=     Set the RPi overclocking mode in config.txt
+  --vc          Install the RPi VC libraries in /opt/vc
+  --nosat       Dont regenerate the distro with sat
 
 EOT
 }
@@ -216,75 +217,63 @@ case "$1" in
 		# partition on the sdcard.
 		: ${flavor=rpi}
 		: ${oclock=none}
-		check_root
-		rm -rf ${rootfs} ${boot}
-		mkdir -p ${boot}
 		
 		# Use the rootfs generated by sat
 		if [ ! -x "/usr/bin/sat" ]; then
 			error "Sat is not installed" && exit 1
 		fi
-		[ "$clean" ] && sat clean --work="$work"
-		if [ ! -d "$distro/rootfs/etc" ]; then
-			sat gen --work="$work" --flavor="$flavor" \
-				--kmap --spk --noinit --rpi
+		
+		# We may want to simply regenerate the RPi distro
+		if [ ! "$nosat" ]; then
+			sat gen --work="$work" --flavor="$flavor" --kmap --noinit --rpi
 		fi
+		
 		header "SliTaz Raspberry Pi distro"
-		dsize="$(du -sh ${distro}/rootfs | awk '{print $1}')"
-		echo -n "Copying: rootfs ($dsize)"
-		cp -a ${distro}/rootfs ${rootfs}; status
 		
 		# Boot firmware
 		echo -n "Copying: firmware files..."
-		get_fw
+		mkdir -p ${boot} && get_fw
 		for fw in $fwlist
 		do
-			cp $firmware/boot/${fw} ${boot}
+			cp ${firmware}/boot/${fw} ${boot}
 		done
 		status
 		
 		# SliTaz Raspberry Pi custom rootfs files. Make sure all files 
 		# belong to root
-		if [ -d "$work/rootfs" ]; then
-			size=$(du -sh $work/rootfs | awk '{print $1}')
+		if [ -d "$rpi/rootfs" ]; then
+			size=$(du -sh $rpi/rootfs | awk '{print $1}')
 			echo -n "Copying: SliTaz RPi rootfs ($size)"
-			tmp=$distro/tmp-$$
-			mkdir -p $tmp
-			cp -r $work/rootfs/* $tmp
-			chown -R root.root $tmp
-			cp -a $tmp/* ${rootfs} && rm -rf $tmp
+			tmp=${distro}/tmp-$$
+			mkdir -p ${tmp}
+			cp -r ${rpi}/rootfs/* ${tmp}
+			chown -R root.root ${tmp}
+			cp -a ${tmp}/* ${rootfs} && rm -rf ${tmp}
+			# Move files to $boot
+			mv -f ${rootfs}/boot/* ${boot}
 			status
 		fi
 		
-		# /boot/config.txt
-		echo -n "Creating: /boot/config.txt"
-		echo 'kernel=kernel.img' > ${boot}/config.txt
+		# Overcloking
+		echo -n "Setting: Overcloking"
 		set_oclock; status
-		if [ "$turbo" ]; then
-			echo "force_turbo=1" >> ${boot}/config.txt
-		fi
 		
-		# /etc/fstab
-		echo -n "Creating: /etc/fstab"
-		cat > ${rootfs}/etc/fstab << EOT
-# /etc/fstab: Slitaz ARM static filesystems.
-#
-proc              /proc       proc     defaults           0 0
-sysfs             /sys        sysfs    defaults           0 0
-/dev/mmcblk0p1    /boot       auto     noauto,noatime     1 2
-/dev/mmcblk0p2    none        swap     sw                 0 0
-/dev/mmcblk0p3    /           ext4     noatime            0 1
-EOT
-		status
+		# Force turbo
+		if [ "$turbo" ]; then
+			echo -n "Config: force_turbo=1"
+			echo "force_turbo=1" >> ${boot}/config.txt; status
+		fi
 		
 		# Kernel
 		kvers=$(ls $data/linux-*/fs/lib/modules)
 		kpkg="$rootfs/var/lib/tazpkg/installed/linux"
-		if [ -d "$data/linux-$kvers/fs" ]; then
-			echo -n "Copying: Linux Kernel $kvers"
+		fs="$data/linux-$kvers/fs"
+		ksize=$(du -sh $fs | awk '{print $1}')
+		if [ -d "$fs" ]; then
+			echo -n "Copying: kernel $kvers ($ksize)"
 			rm -rf ${rootfs}/lib/modules
-			cp -rf ${data}/linux-${kvers}/fs/lib/* ${rootfs}/lib
-			cp -f  ${data}/linux-${kvers}/fs/boot/* ${boot}
+			cp -rf ${fs}/lib/* ${rootfs}/lib
+			cp -f  ${fs}/boot/* ${boot}
 			mkdir -p ${kpkg}
 			cd ${data}/linux-${kvers}
 			cp -f files.list md5sum receipt ${kpkg}
@@ -292,12 +281,20 @@ EOT
 		else
 			echo "RPi Kernel: not used"
 		fi
-		mkdir -p ${rootfs}/boot
 		
 		# RPi VC libraries
 		if [ "$vc" ]; then
-			echo "Installing: VC libraries"
-			echo "TODO"
+			if [ ! -d "$firmware/opt/vc" ]; then
+				error "Missing firmware git repository" && exit 1
+			fi
+			# --hardfp
+			if [ "$hardfp" ]; then
+				echo -n "Not yet supported: SliTaz ARMv6hf"; false
+			else
+				echo -n "Installing standard: VC libraries"
+				cp -a ${firmware}/opt ${rootfs}
+			fi
+			status
 		fi
 		
 		separator
@@ -315,9 +312,12 @@ EOT
 			error "Missing cross toolchain in: /cross/$arch"
 			exit 1
 		fi
+		
 		# Kernel source
+		cd ${rpi_git}
 		[ -d "$kernel" ] || git clone --depth 1 ${rpi_git_url}linux.git
 		
+		# Compile
 		if [ ! -d "$install" ]; then
 			cd ${kernel}
 			export PATH=$PATH:/cross/${arch}/tools/bin
@@ -331,9 +331,12 @@ EOT
 			cp -a arch/arm/boot/zImage ${install}/boot
 		fi
 		
-		# Compress all modules
-		#echo -n "Searching all modules to compress them... "
-		#find . -name "*.ko" -exec xz '{}' \; 2> /dev/null
+		# Compress modules
+		mods=$(find . -name "*.ko" | wc -l)
+		newline
+		echo "Kernel modules: $mods"
+		#echo -n "Compressing modules: $mods"
+		#find . -name "*.ko" -exec gz '{}' \; 2> /dev/null
 		
 		# Pack
 		fs="$data/linux-$kvers/fs"
@@ -374,6 +377,8 @@ EOT
 		# Precook RPi kernel
 		mkdir -p ${data}
 		rm -f ${data}/linux-version.txt
+		
+		# Last version
 		if busybox wget -q -s ${rpi_mirror}/last-linux.txt; then
 			echo -n "Fetching latest Kernel string..."
 			wget -q ${rpi_mirror}/last-linux.txt \
@@ -385,16 +390,19 @@ EOT
 		kvers=$(cat $data/linux-version.txt)
 		[ "$up" ] && rm -rf ${data}/linux-${kvers}*
 		echo "Kernel version: $kvers"
+		
 		# Download
 		if [ ! -f "$data/linux-$kvers.tazpkg" ]; then
 			echo -n "Fetching latest Linux package..."
 			wget -q ${rpi_mirror}/linux-${kvers}.tazpkg \
 				-O ${data}/linux-${kvers}.tazpkg; status
 		fi
+		
 		# Extract
 		if [ ! -d "$data/linux-$kvers" ]; then
 			cd ${data} && tazpkg extract linux-${kvers}.tazpkg
-		fi ;;
+		fi 
+		rm -f ${data}/linux-version.txt ;;
 		
 	get-prebuilt)
 		# --> in cross ??
